const projectSingle = {
  url: 'https://homepages.cae.wisc.edu/~ece533/images/fruits.png',
  profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
  title: 'Monthly mediataion ...',
  time: '2 days ago',
};

export const testImageArray = [
  {url: require('../assets/imageOne.jpeg')},
  {url: require('../assets/imageTwo.jpg')},
  {url: require('../assets/imageThree.jpg')},
  {url: require('../assets/imageFour.jpg')},
  {url: require('../assets/imageFive.jpg')},
  {url: require('../assets/imageSix.jpg')},
  {url: require('../assets/imageSeven.jpg')},
  {url: require('../assets/imageEight.jpg')},
  {url: require('../assets/imageNine.jpg')},
  {url: require('../assets/imageTen.jpg')},
  {url: require('../assets/imageEleven.jpg')},
  {url: require('../assets/imageTwelve.jpg')},
];

export const projectArray = [
  {
    url: require('../assets/project1.jpg'),
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'friendsoftheearth',
    detail: 'Walking through the park earlier, found friendly squirrel ',
    worldImage: require('../assets/planetBlue.png'),
    hasButton: false,
    isVerified: false,
    id: '0',
    interest: 'Zero Hunger',
    title: 'Adapt a turtle...',
    coins: '47',
    time: '4 hrs ago',
    date: '04/05/21',
    projectTypeUrl: require('../assets/planetBlue.png'),
    isPlanet: true,
  },
  {
    url: require('../assets/project2.jpg'),
    title: 'Adapting a pengu..',
    time: '1 day ago',
    coins: '45',
    projectTypeUrl: require('../assets/peoplePink.png'),
    date: '01/05/21',
    isPlanet: false,
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'friendsoftheearth',
    detail: 'Walking through the park earlier, found friendly squirrel ',
    worldImage: require('../assets/planetBlue.png'),
    hasButton: true,
    isVerified: true,
    id: '0',
    interest: 'Zero Hunger',
  },
  {
    url: require('../assets/project3.jpg'),
    title: 'Houseplants prod...',
    time: '24 hrs ago',
    coins: '39',
    date: '30/04/21',
    projectTypeUrl: require('../assets/planetBlue.png'),
    isPlanet: true,
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'friendsoftheearth',
    detail: 'Walking through the park earlier, found friendly squirrel ',
    worldImage: require('../assets/planetBlue.png'),
    hasButton: false,
    isVerified: false,
    id: '0',
    interest: 'Zero Hunger',
  },
  {
    url: require('../assets/project4.jpg'),
    title: 'Save the Rainfo...',
    time: '4 hrs ago',
    coins: '90',
    projectTypeUrl: require('../assets/peoplePink.png'),
    date: '29/04/21',
    isPlanet: false,
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'friendsoftheearth',
    detail: 'Walking through the park earlier, found friendly squirrel ',
    worldImage: require('../assets/planetBlue.png'),
    hasButton: true,
    isVerified: true,
    id: '0',
    interest: 'Zero Hunger',
  },
  {
    url: require('../assets/project5.jpg'),
    title: 'Treeplanting to co...',
    time: '4 hrs ago',
    coins: '60',
    date: '26/04/21',
    projectTypeUrl: require('../assets/planetBlue.png'),
    isPlanet: true,
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'friendsoftheearth',
    detail: 'Walking through the park earlier, found friendly squirrel ',
    worldImage: require('../assets/planetBlue.png'),
    hasButton: false,
    isVerified: false,
    id: '0',
    interest: 'Zero Hunger',
  },
  {
    url: require('../assets/project6.jpg'),
    title: 'Adapt a turtle...',
    time: '4 hrs ago',
    coins: '20',
    date: '15/04/21',
    projectTypeUrl: require('../assets/peoplePink.png'),
    isPlanet: false,
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'friendsoftheearth',
    detail: 'Walking through the park earlier, found friendly squirrel ',
    worldImage: require('../assets/planetBlue.png'),
    hasButton: true,
    isVerified: true,
    id: '0',
    interest: 'Zero Hunger',
  },
  {
    url: require('../assets/project7.jpg'),
    title: 'Adapt a turtle...',
    coins: '47',
    time: '4 hrs ago',
    date: '04/05/21',
    projectTypeUrl: require('../assets/planetBlue.png'),
    isPlanet: true,
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'friendsoftheearth',
    detail: 'Walking through the park earlier, found friendly squirrel ',
    worldImage: require('../assets/planetBlue.png'),
    hasButton: false,
    isVerified: false,
    id: '0',
    interest: 'Zero Hunger',
  },
  {
    url: require('../assets/project8.jpg'),
    title: 'Houseplants prod...',
    time: '1 day ago',
    coins: '45',
    date: '01/05/21',
    projectTypeUrl: require('../assets/peoplePink.png'),
    isPlanet: false,
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'friendsoftheearth',
    detail: 'Walking through the park earlier, found friendly squirrel ',
    worldImage: require('../assets/planetBlue.png'),
    hasButton: true,
    isVerified: true,
    id: '0',
    interest: 'Zero Hunger',
  },
  {
    url: require('../assets/project9.jpg'),
    title: 'WWF planet aware...',
    time: '24 hrs ago',
    coins: '39',
    date: '30/04/21',
    projectTypeUrl: require('../assets/planetBlue.png'),
    isPlanet: true,
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'friendsoftheearth',
    detail: 'Walking through the park earlier, found friendly squirrel ',
    worldImage: require('../assets/planetBlue.png'),
    hasButton: false,
    isVerified: false,
    id: '0',
    interest: 'Zero Hunger',
  },
  {
    url: require('../assets/project10.jpg'),
    title: 'Save the sloths to...',
    time: '4 hrs ago',
    coins: '90',
    date: '29/04/21',
    projectTypeUrl: require('../assets/peoplePink.png'),
    isPlanet: false,
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'friendsoftheearth',
    detail: 'Walking through the park earlier, found friendly squirrel ',
    worldImage: require('../assets/planetBlue.png'),
    hasButton: true,
    isVerified: true,
    id: '0',
    interest: 'Zero Hunger',
  },
  {
    url: require('../assets/project11.jpg'),
    title: 'Cleaning Sust...',
    time: '4 hrs ago',
    coins: '60',
    date: '26/04/21',
    projectTypeUrl: require('../assets/planetBlue.png'),
    isPlanet: true,
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'friendsoftheearth',
    detail: 'Walking through the park earlier, found friendly squirrel ',
    worldImage: require('../assets/planetBlue.png'),
    hasButton: false,
    isVerified: false,
    id: '0',
    interest: 'Zero Hunger',
  },
  {
    url: require('../assets/project12.jpg'),
    title: 'Growing home gro...',
    time: '4 hrs ago',
    coins: '20',
    date: '15/04/21',
    projectTypeUrl: require('../assets/peoplePink.png'),
    isPlanet: false,
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'friendsoftheearth',
    detail: 'Walking through the park earlier, found friendly squirrel ',
    worldImage: require('../assets/planetBlue.png'),
    hasButton: true,
    isVerified: true,
    id: '0',
    interest: 'Zero Hunger',
  },
  {
    url: require('../assets/project1.jpg'),
    title: 'Adapt a turtle...',
    coins: '47',
    time: '4 hrs ago',
    date: '04/05/21',
    projectTypeUrl: require('../assets/planetBlue.png'),
    isPlanet: true,
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'friendsoftheearth',
    detail: 'Walking through the park earlier, found friendly squirrel ',
    worldImage: require('../assets/planetBlue.png'),
    hasButton: false,
    isVerified: false,
    id: '0',
    interest: 'Zero Hunger',
  },
  {
    url: require('../assets/project2.jpg'),
    title: 'Adapting a penguin..',
    time: '1 day ago',
    coins: '45',
    date: '01/05/21',
    projectTypeUrl: require('../assets/peoplePink.png'),
    isPlanet: false,
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'friendsoftheearth',
    detail: 'Walking through the park earlier, found friendly squirrel ',
    worldImage: require('../assets/planetBlue.png'),
    hasButton: true,
    isVerified: true,
    id: '0',
    interest: 'Zero Hunger',
  },
  {
    url: require('../assets/project3.jpg'),
    title: 'Houseplants produc...',
    time: '24 hrs ago',
    coins: '39',
    date: '30/04/21',
    projectTypeUrl: require('../assets/planetBlue.png'),
    isPlanet: true,
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'friendsoftheearth',
    detail: 'Walking through the park earlier, found friendly squirrel ',
    worldImage: require('../assets/planetBlue.png'),
    hasButton: false,
    isVerified: false,
    id: '0',
    interest: 'Zero Hunger',
  },
  {
    url: require('../assets/project12.jpg'),
    title: 'Growing home gro...',
    time: '4 hrs ago',
    coins: '20',
    date: '15/04/21',
    projectTypeUrl: require('../assets/peoplePink.png'),
    isPlanet: false,
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'friendsoftheearth',
    detail: 'Walking through the park earlier, found friendly squirrel ',
    worldImage: require('../assets/planetBlue.png'),
    hasButton: true,
    isVerified: true,
    id: '0',
    interest: 'Zero Hunger',
  },
  {
    url: require('../assets/project1.jpg'),
    title: 'Adapt a turtle...',
    coins: '47',
    time: '4 hrs ago',
    date: '04/05/21',
    projectTypeUrl: require('../assets/planetBlue.png'),
    isPlanet: true,
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'friendsoftheearth',
    detail: 'Walking through the park earlier, found friendly squirrel ',
    worldImage: require('../assets/planetBlue.png'),
    hasButton: false,
    isVerified: false,
    id: '0',
    interest: 'Zero Hunger',
  },
  {
    url: require('../assets/project2.jpg'),
    title: 'Adapting a penguin..',
    time: '1 day ago',
    coins: '45',
    date: '01/05/21',
    projectTypeUrl: require('../assets/peoplePink.png'),
    isPlanet: false,
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'friendsoftheearth',
    detail: 'Walking through the park earlier, found friendly squirrel ',
    worldImage: require('../assets/planetBlue.png'),
    hasButton: true,
    isVerified: true,
    id: '0',
    interest: 'Zero Hunger',
  },
  {
    url: require('../assets/project3.jpg'),
    title: 'Houseplants produc...',
    time: '24 hrs ago',
    coins: '39',
    date: '30/04/21',
    projectTypeUrl: require('../assets/planetBlue.png'),
    isPlanet: true,
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'friendsoftheearth',
    detail: 'Walking through the park earlier, found friendly squirrel ',
    worldImage: require('../assets/planetBlue.png'),
    hasButton: false,
    isVerified: false,
    id: '0',
    interest: 'Zero Hunger',
  },
  {
    url: require('../assets/project2.jpg'),
    title: 'Adapting a penguin..',
    time: '1 day ago',
    coins: '45',
    date: '01/05/21',
    projectTypeUrl: require('../assets/peoplePink.png'),
    isPlanet: false,
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'friendsoftheearth',
    detail: 'Walking through the park earlier, found friendly squirrel ',
    worldImage: require('../assets/planetBlue.png'),
    hasButton: true,
    isVerified: true,
    id: '0',
    interest: 'Zero Hunger',
  },
];

export const walletArray = [
  {
    url: require('../assets/search10.jpg'),
    title: 'Meditation to rel...',
    coins: '47',
    time: '4 hrs ago',
    date: '04/05/21',
    isPlanet: true,
  },
  {
    url: require('../assets/search1.jpg'),
    title: 'Cycle for mental...',
    time: '1 day ago',
    coins: '45',
    date: '01/05/21',
    isPlanet: false,
  },
  {
    url: require('../assets/search7.jpg'),
    title: 'Self Care Day',
    time: '24 hrs ago',
    coins: '39',
    date: '30/04/21',
    isPlanet: true,
  },
  {
    url: require('../assets/search3.jpg'),
    title: 'Girl Power',
    time: '4 hrs ago',
    coins: '90',
    date: '29/04/21',
    isPlanet: false,
  },
  {
    url: require('../assets/search5.jpg'),
    title: 'Helping OAPs with tech',
    time: '4 hrs ago',
    coins: '60',
    date: '26/04/21',
    isPlanet: true,
  },
  {
    url: require('../assets/search7.jpg'),
    title: 'Weekly Meditation',
    time: '4 hrs ago',
    coins: '20',
    date: '15/04/21',
    isPlanet: false,
  },
  {
    url: require('../assets/search10.jpg'),
    title: 'Meditation to rel...',
    coins: '47',
    time: '4 hrs ago',
    date: '04/05/21',
    isPlanet: true,
  },
  {
    url: require('../assets/search1.jpg'),
    title: 'Cycle for mental...',
    time: '1 day ago',
    coins: '45',
    date: '01/05/21',
    isPlanet: false,
  },
  {
    url: require('../assets/search7.jpg'),
    title: 'Self Care Day',
    time: '24 hrs ago',
    coins: '39',
    date: '30/04/21',
    isPlanet: true,
  },
  {
    url: require('../assets/search3.jpg'),
    title: 'Girl Power',
    time: '4 hrs ago',
    coins: '90',
    date: '29/04/21',
    isPlanet: false,
  },
  {
    url: require('../assets/search5.jpg'),
    title: 'Helping OAPs with tech',
    time: '4 hrs ago',
    coins: '60',
    date: '26/04/21',
    isPlanet: true,
  },
  {
    url: require('../assets/search7.jpg'),
    title: 'Weekly Meditation',
    time: '4 hrs ago',
    coins: '20',
    date: '15/04/21',
    isPlanet: false,
  },
  {
    url: require('../assets/search3.jpg'),
    title: 'Girl Power',
    time: '4 hrs ago',
    coins: '90',
    date: '29/04/21',
    isPlanet: true,
  },
  {
    url: require('../assets/search5.jpg'),
    title: 'Helping OAPs with tech',
    time: '4 hrs ago',
    coins: '60',
    date: '26/04/21',
    isPlanet: false,
  },
  {
    url: require('../assets/search7.jpg'),
    title: 'Weekly Meditation',
    time: '4 hrs ago',
    coins: '20',
    date: '15/04/21',
    isPlanet: true,
  },
  {
    url: require('../assets/search3.jpg'),
    title: 'Girl Power',
    time: '4 hrs ago',
    coins: '90',
    date: '29/04/21',
    isPlanet: false,
  },
  {
    url: require('../assets/search5.jpg'),
    title: 'Helping OAPs with tech',
    time: '4 hrs ago',
    coins: '60',
    date: '26/04/21',
    isPlanet: true,
  },
  {
    url: require('../assets/search7.jpg'),
    title: 'Weekly Meditation',
    time: '4 hrs ago',
    coins: '20',
    date: '15/04/21',
    isPlanet: false,
  },
];

export const searchArray = [
  {
    title: 'peopleproject',
    total: 208,
    images: [
      {
        url: require('../assets/search7.jpg'),
        title: 'Meditation to rel...',
        time: '4 hrs ago',
        projectTypeUrl: require('../assets/peoplePink.png'),
        profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
        name: 'friendsofthearth',
        detail: 'Walking through the park earlier, found friendly squirrel ',
        worldImage: require('../assets/peoplePink.png'),
        hasButton: false,
        isVerified: false,
        id: '0',
        date: '05.05.21',
        interest: 'Zero Hunger',
      },
      {
        url: require('../assets/search12.jpg'),
        title: 'Cycle for mental...',
        time: '1 day ago',
        projectTypeUrl: require('../assets/planetBlue.png'),
        profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
        name: 'friendsofthearth',
        detail: 'Walking through the park earlier, found friendly squirrel ',
        worldImage: require('../assets/planetBlue.png'),
        hasButton: true,
        isVerified: true,
        id: '0',
        date: '05.05.21',
        interest: 'Zero Hunger',
      },
      {
        url: require('../assets/search11.jpg'),
        title: 'Manchester marat...',
        time: '24 hrs ago',
        projectTypeUrl: require('../assets/peoplePink.png'),
        profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
        name: 'friendsofthearth',
        detail: 'Walking through the park earlier, found friendly squirrel ',
        worldImage: require('../assets/peoplePink.png'),
        hasButton: false,
        isVerified: false,
        id: '0',
        date: '05.05.21',
        interest: 'Zero Hunger',
      },
      {
        url: require('../assets/search8.jpg'),
        title: 'Meditation to rel...',
        time: '4 hrs ago',
        projectTypeUrl: require('../assets/planetBlue.png'),
        profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
        name: 'friendsofthearth',
        detail: 'Walking through the park earlier, found friendly squirrel ',
        worldImage: require('../assets/planetBlue.png'),
        hasButton: true,
        isVerified: true,
        id: '0',
        date: '05.05.21',
        interest: 'Zero Hunger',
      },
      {
        url: require('../assets/search9.jpg'),
        title: 'Meditation to rel...',
        time: '4 hrs ago',
        projectTypeUrl: require('../assets/peoplePink.png'),
        profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
        name: 'friendsofthearth',
        detail: 'Walking through the park earlier, found friendly squirrel ',
        worldImage: require('../assets/peoplePink.png'),
        hasButton: false,
        isVerified: false,
        id: '0',
        date: '05.05.21',
        interest: 'Zero Hunger',
      },
    ],
  },
  {
    title: 'selflove',
    total: 256,
    images: [
      {
        url: require('../assets/search1.jpg'),
        title: 'Self Care Day',
        time: '4 hrs ago',
        projectTypeUrl: require('../assets/planetBlue.png'),
        profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
        name: 'friendsofthearth',
        detail: 'Walking through the park earlier, found friendly squirrel ',
        worldImage: require('../assets/planetBlue.png'),
        hasButton: true,
        isVerified: true,
        id: '0',
        date: '05.05.21',
        interest: 'Zero Hunger',
      },
      {
        url: require('../assets/search2.jpg'),
        title: 'Enjoy the great out...',
        time: '1 day ago',
        projectTypeUrl: require('../assets/peoplePink.png'),
        profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
        name: 'friendsofthearth',
        detail: 'Walking through the park earlier, found friendly squirrel ',
        worldImage: require('../assets/peoplePink.png'),
        hasButton: false,
        isVerified: false,
        id: '0',
        date: '05.05.21',
        interest: 'Zero Hunger',
      },
      {
        url: require('../assets/search3.jpg'),
        title: 'Girl Power',
        time: '24 hrs ago',
        projectTypeUrl: require('../assets/planetBlue.png'),
        profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
        name: 'friendsofthearth',
        detail: 'Walking through the park earlier, found friendly squirrel ',
        worldImage: require('../assets/planetBlue.png'),
        hasButton: true,
        isVerified: true,
        id: '0',
        date: '05.05.21',
        interest: 'Zero Hunger',
      },
      {
        url: require('../assets/search8.jpg'),
        title: 'Meditation to rel...',
        time: '4 hrs ago',
        projectTypeUrl: require('../assets/peoplePink.png'),
        profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
        name: 'friendsofthearth',
        detail: 'Walking through the park earlier, found friendly squirrel ',
        worldImage: require('../assets/peoplePink.png'),
        hasButton: false,
        isVerified: false,
        id: '0',
        date: '05.05.21',
        interest: 'Zero Hunger',
      },
      {
        url: require('../assets/search9.jpg'),
        title: 'Meditation to rel...',
        time: '4 hrs ago',
        projectTypeUrl: require('../assets/planetBlue.png'),
        profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
        name: 'friendsofthearth',
        detail: 'Walking through the park earlier, found friendly squirrel ',
        worldImage: require('../assets/planetBlue.png'),
        hasButton: true,
        isVerified: true,
        id: '0',
        date: '05.05.21',
        interest: 'Zero Hunger',
      },
    ],
  },
  {
    title: 'communitysupport',
    total: 799,
    images: [
      {
        url: require('../assets/search10.jpg'),
        title: 'Community Supp...',
        time: '4 hrs ago',
        projectTypeUrl: require('../assets/peoplePink.png'),
        profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
        name: 'friendsofthearth',
        detail: 'Walking through the park earlier, found friendly squirrel ',
        worldImage: require('../assets/peoplePink.png'),
        hasButton: false,
        isVerified: false,
        id: '0',
        date: '05.05.21',
        interest: 'Zero Hunger',
      },
      {
        url: require('../assets/search6.jpg'),
        title: 'Technology Heroes...',
        time: '1 day ago',
        projectTypeUrl: require('../assets/planetBlue.png'),
        profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
        name: 'friendsofthearth',
        detail: 'Walking through the park earlier, found friendly squirrel ',
        worldImage: require('../assets/planetBlue.png'),
        hasButton: true,
        isVerified: true,
        id: '0',
        date: '05.05.21',
        interest: 'Zero Hunger',
      },
      {
        url: require('../assets/search5.jpg'),
        title: 'Be Kind to those...',
        time: '24 hrs ago',
        projectTypeUrl: require('../assets/peoplePink.png'),
        profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
        name: 'friendsofthearth',
        detail: 'Walking through the park earlier, found friendly squirrel ',
        worldImage: require('../assets/peoplePink.png'),
        hasButton: false,
        isVerified: false,
        id: '0',
        date: '05.05.21',
        interest: 'Zero Hunger',
      },
      {
        url: require('../assets/search8.jpg'),
        title: 'Meditation to rel...',
        time: '4 hrs ago',
        projectTypeUrl: require('../assets/planetBlue.png'),
        profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
        name: 'friendsofthearth',
        detail: 'Walking through the park earlier, found friendly squirrel ',
        worldImage: require('../assets/planetBlue.png'),
        hasButton: true,
        isVerified: true,
        id: '0',
        date: '05.05.21',
        interest: 'Zero Hunger',
      },
      {
        url: require('../assets/search9.jpg'),
        title: 'Meditation to rel...',
        time: '4 hrs ago',
        projectTypeUrl: require('../assets/peoplePink.png'),
        profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
        name: 'friendsofthearth',
        detail: 'Walking through the park earlier, found friendly squirrel ',
        worldImage: require('../assets/peoplePink.png'),
        hasButton: false,
        isVerified: false,
        id: '0',
        date: '05.05.21',
        interest: 'Zero Hunger',
      },
    ],
  },
  {
    title: 'healthylifestyle',
    total: 256,
    images: [
      {
        url: require('../assets/search8.jpg'),
        title: 'Sustainable Cloth...',
        time: '4 hrs ago',
        projectTypeUrl: require('../assets/planetBlue.png'),
        profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
        name: 'friendsofthearth',
        detail: 'Walking through the park earlier, found friendly squirrel ',
        worldImage: require('../assets/peoplePink.png'),
        hasButton: true,
        isVerified: true,
        id: '0',
        date: '05.05.21',
        interest: 'Zero Hunger',
      },
      {
        url: require('../assets/search4.jpg'),
        title: 'Smoothie Week...',
        time: '1 day ago',
        projectTypeUrl: require('../assets/peoplePink.png'),
        profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
        name: 'friendsofthearth',
        detail: 'Walking through the park earlier, found friendly squirrel ',
        worldImage: require('../assets/peoplePink.png'),
        hasButton: false,
        isVerified: false,
        id: '0',
        date: '05.05.21',
        interest: 'Zero Hunger',
      },
      {
        url: require('../assets/search9.jpg'),
        title: 'Health Check In',
        time: '24 hrs ago',
        projectTypeUrl: require('../assets/planetBlue.png'),
        profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
        name: 'friendsofthearth',
        detail: 'Walking through the park earlier, found friendly squirrel ',
        worldImage: require('../assets/planetBlue.png'),
        hasButton: true,
        isVerified: true,
        id: '0',
        date: '05.05.21',
        interest: 'Zero Hunger',
      },
      {
        url: require('../assets/search8.jpg'),
        title: 'Meditation to rel...',
        time: '4 hrs ago',
        projectTypeUrl: require('../assets/peoplePink.png'),
        profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
        name: 'friendsofthearth',
        detail: 'Walking through the park earlier, found friendly squirrel ',
        worldImage: require('../assets/peoplePink.png'),
        hasButton: false,
        isVerified: false,
        id: '0',
        date: '05.05.21',
        interest: 'Zero Hunger',
      },
      {
        url: require('../assets/search9.jpg'),
        title: 'Meditation to rel...',
        time: '4 hrs ago',
        projectTypeUrl: require('../assets/planetBlue.png'),
        profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
        name: 'friendsofthearth',
        detail: 'Walking through the park earlier, found friendly squirrel ',
        worldImage: require('../assets/planetBlue.png'),
        hasButton: true,
        isVerified: true,
        id: '0',
        date: '05.05.21',
        interest: 'Zero Hunger',
      },
    ],
  },
];

export const inboxArray = [
  {
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'Beth Hall',
    id: '0',
    time: '34m',
    type: 'project',
  },
  {
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'Sarah Alderidge',
    id: '0',
    time: '1w',
    type: 'post',
  },
  {
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'Yvonne Chin',
    id: '0',
    time: '1h',
    type: 'project',
  },
  {
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'Susanna Fonte',
    id: '0',
    time: '1d',
    type: 'post',
  },
  {
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'Matt Williams',
    id: '0',
    time: '2d',
    type: 'project',
  },
  {
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'Beth Hall',
    id: '0',
    time: '34m',
    type: 'project',
  },
  {
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'Sarah Alderidge',
    id: '0',
    time: '1w',
    type: 'post',
  },
  {
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'Yvonne Chin',
    id: '0',
    time: '1h',
    type: 'project',
  },
  {
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'Susanna Fonte',
    id: '0',
    time: '1d',
    type: 'post',
  },
  {
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'Matt Williams',
    id: '0',
    time: '2d',
    type: 'project',
  },
];

export const imageArray = [
  {
    url: require('../assets/homeSlideOne.jpg'),
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'wunder',
    title: 'Healthy Eating',
    detail: 'Walking through the park earlier, found friendly squirrel ',
    worldImage: require('../assets/planetBlue.png'),
    hasButton: false,
    isVerified: false,
    id: '0',
    time: '4 hrs ago',
    date: '05.05.21',
    interest: 'Zero Hunger',
  },
  {
    url: require('../assets/homeSlideTwo.jpg'),
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'greatermondst',
    title: 'Peaceful walk this morning',
    detail: 'Walking through the park earlier, found friendly squirrel ',
    worldImage: require('../assets/peoplePink.png'),
    hasButton: true,
    isVerified: true,
    id: '1',
    time: '4 hrs ago',
    date: '05.05.21',
    interest: 'Good Health & Wellbeing',
  },
  {
    url: require('../assets/imageNine.jpg'),
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'friendsoftheearth',
    title: 'Peaceful walk this morning',
    detail: 'Walking through the park earlier, found friendly squirrel ',
    worldImage: require('../assets/planetBlue.png'),
    hasButton: false,
    isVerified: true,
    id: '2',
    time: '4 hrs ago',
    date: '05.05.21',
    interest: 'Quality Education',
  },
  {
    url: require('../assets/imageFour.jpg'),
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'vic_azerrence',
    title: 'Peaceful walk this morning',
    detail: 'Walking through the park earlier, found friendly squirrel ',
    worldImage: require('../assets/peoplePink.png'),
    hasButton: true,
    isVerified: false,
    id: '3',
    time: '4 hrs ago',
    date: '03.05.21',
    interest: 'Gender Equality',
  },
  {
    url: require('../assets/imageThree.jpg'),
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'tescoofficial',
    title: 'Peaceful walk this morning',
    detail: 'Walking through the park earlier, found friendly squirrel ',
    worldImage: require('../assets/planetBlue.png'),
    hasButton: false,
    isVerified: true,
    id: '4',
    time: '4 hrs ago',
    date: '01.05.21',
    interest: 'Clean water & Sanitation',
  },
  {
    url: require('../assets/imageTwelve.jpg'),
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'sam_williams',
    title: 'Peaceful walk this morning',
    detail: 'Walking through the park earlier, found friendly squirrel ',
    worldImage: require('../assets/peoplePink.png'),
    hasButton: true,
    isVerified: false,
    id: '5',
    time: '4 hrs ago',
    date: '02.05.21',
    interest: 'Climate Action',
  },
  {
    url: require('../assets/imageFive.jpg'),
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'millissaharris10',
    title: 'Peaceful walk this morning',
    detail: 'Walking through the park earlier, found friendly squirrel ',
    worldImage: require('../assets/planetBlue.png'),
    hasButton: true,
    isVerified: true,
    id: '6',
    time: '4 hrs ago',
    date: '05.05.21',
    interest: 'Good Health & Wellbeing',
  },
  {
    url: require('../assets/imageSeven.jpg'),
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'nora_osborn',
    title: 'Peaceful walk this morning',
    detail: 'Walking through the park earlier, found friendly squirrel ',
    worldImage: require('../assets/peoplePink.png'),
    hasButton: false,
    isVerified: true,
    id: '7',
    time: '4 hrs ago',
    date: '05.05.21',
    interest: 'Quality Education',
  },
  {
    url: require('../assets/imageSix.jpg'),
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'Promit',
    title: 'Peaceful walk this morning',
    detail: 'Walking through the park earlier, found friendly squirrel ',
    worldImage: require('../assets/planetBlue.png'),
    hasButton: true,
    isVerified: false,
    id: '8',
    time: '4 hrs ago',
    date: '03.05.21',
    interest: 'Gender Equality',
  },
  {
    url: require('../assets/imageTwo.jpg'),
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'Promit',
    title: 'Peaceful walk this morning',
    detail: 'Walking through the park earlier, found friendly squirrel ',
    worldImage: require('../assets/peoplePink.png'),
    hasButton: false,
    isVerified: true,
    id: '9',
    time: '4 hrs ago',
    date: '01.05.21',
    interest: 'Clean water & Sanitation',
  },
  {
    url: require('../assets/imageNine.jpg'),
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'Promit',
    title: 'Peaceful walk this morning',
    detail: 'Walking through the park earlier, found friendly squirrel ',
    worldImage: require('../assets/planetBlue.png'),
    hasButton: true,
    isVerified: false,
    id: '10',
    time: '4 hrs ago',
    date: '02.05.21',
    interest: 'Climate Action',
  },
  {
    url: require('../assets/imageOne.jpeg'),
    profileImageUrl: 'https://reactnative.dev/img/tiny_logo.png',
    name: 'Promit',
    title: 'Peaceful walk this morning',
    detail: 'Walking through the park earlier, found friendly squirrel ',
    worldImage: require('../assets/peoplePink.png'),
    hasButton: false,
    isVerified: false,
    id: '11',
    time: '4 hrs ago',
    date: '05.05.21',
    interest: 'Zero Hunger',
  },
];

export const newPostItemArray = [
  {
    title: 'Tag People',
    showRightIcon: true,
    showLeftIcon: false,
  },
  {
    title: 'Location',
    showRightIcon: true,
    showLeftIcon: false,
  },
  {
    title: 'People',
    showRightIcon: false,
    showLeftIcon: false,
  },
  {
    title: 'Planet',
    showRightIcon: false,
    showLeftIcon: false,
  },
  {
    title: 'Save for later?',
    showRightIcon: false,
    showLeftIcon: false,
  },
  {
    title: 'Advanced Settings',
    showRightIcon: true,
    showLeftIcon: false,
  },
];

export const aboutItemArray = [
  {
    title: 'Data Policy',
    iconName: 'twitter',
    iconType: 'entypo',
    showRightIcon: true,
    showLeftIcon: false,
  },
  {
    title: 'Terms of Use',
    iconName: 'twitter',
    iconType: 'entypo',
    showRightIcon: true,
    showLeftIcon: false,
  },
];

export const helpItemsArray = [
  {
    title: 'Report a problem',
    iconName: 'sc-facebook',
    iconType: 'evilicon',
    showRightIcon: true,
    showLeftIcon: false,
  },
  {
    title: 'Help Centre',
    iconName: 'instagram',
    iconType: 'feather',
    showRightIcon: true,
    showLeftIcon: false,
  },
  {
    title: 'Support requests',
    iconName: 'twitter',
    iconType: 'entypo',
    showRightIcon: true,
    showLeftIcon: false,
  },
  {
    title: 'Privacy and security help',
    iconName: 'twitter',
    iconType: 'entypo',
    showRightIcon: true,
    showLeftIcon: false,
  },
];

export const socialItemsArray = [
  {
    title: 'Facebook',
    iconName: 'sc-facebook',
    iconType: 'evilicon',
    showRightIcon: true,
    showLeftIcon: true,
  },
  {
    title: 'Instagram',
    iconName: 'instagram',
    iconType: 'feather',
    showRightIcon: true,
    showLeftIcon: true,
  },
  {
    title: 'Twitter',
    iconName: 'twitter',
    iconType: 'entypo',
    showRightIcon: true,
    showLeftIcon: true,
  },
];

export const privacyItemArray = [
  {
    title: 'Private Account',
    iconName: 'account',
    iconType: 'material-community',
    showRightIcon: false,
    showLeftIcon: false,
  },
  {
    title: 'Interactions',
    iconName: 'account',
    iconType: 'material-community',
    showRightIcon: true,
    showLeftIcon: false,
  },
  {
    title: 'Mentions',
    iconName: 'account',
    iconType: 'material-community',
    showRightIcon: true,
    showLeftIcon: false,
  },
  {
    title: 'Restricted Accounts',
    iconName: 'account',
    iconType: 'material-community',
    showRightIcon: true,
    showLeftIcon: false,
  },
  {
    title: 'Blocked Accounts',
    iconName: 'account',
    iconType: 'material-community',
    showRightIcon: true,
    showLeftIcon: false,
  },
  {
    title: 'Muted Accounts',
    iconName: 'account',
    iconType: 'material-community',
    showRightIcon: true,
    showLeftIcon: false,
  },
  {
    title: 'Accounts you Follow',
    iconName: 'account',
    iconType: 'material-community',
    showRightIcon: true,
    showLeftIcon: false,
  },
];

export const interestsArray = [
  {
    title: 'Zero Hunger',
    iconName: 'coffee',
    iconType: 'feather',
    showRightIcon: false,
    showLeftIcon: true,
  },
  {
    title: 'Good Health & Wellbeing',
    iconName: 'plus',
    iconType: 'font-awesome',
    showRightIcon: false,
    showLeftIcon: true,
  },
  {
    title: 'Quality Education',
    iconName: 'book-open',
    iconType: 'feather',
    showRightIcon: false,
    showLeftIcon: true,
  },
  {
    title: 'Gender Equality',
    iconName: 'transgender-alt',
    iconType: 'font-awesome-5',
    showRightIcon: false,
    showLeftIcon: true,
  },
  {
    title: 'Clean Water & Sanitation',
    iconName: 'water',
    iconType: 'ionicon',
    showRightIcon: false,
    showLeftIcon: true,
  },
  {
    title: 'Climate Action',
    iconName: 'align-horizontal-middle',
    iconType: 'entypo',
    showRightIcon: false,
    showLeftIcon: true,
  },
  {
    title: 'Life on Land',
    iconName: 'foot',
    iconType: 'foundation',
    showRightIcon: false,
    showLeftIcon: true,
  },
  {
    title: 'LGBTQ+',
    iconName: 'rainbow',
    iconType: 'entypo',
    showRightIcon: false,
    showLeftIcon: true,
  },
];

export const notificationsItemArray = [
  {
    title: 'Pause All',
    iconName: 'account',
    iconType: 'material-community',
    showRightIcon: false,
    showLeftIcon: false,
  },
  {
    title: 'Coins Received',
    iconName: 'account',
    iconType: 'material-community',
    showRightIcon: false,
    showLeftIcon: false,
  },
  {
    title: 'Applauds',
    iconName: 'account',
    iconType: 'material-community',
    showRightIcon: false,
    showLeftIcon: false,
  },
  {
    title: 'Comments',
    iconName: 'account',
    iconType: 'material-community',
    showRightIcon: false,
    showLeftIcon: false,
  },
  {
    title: 'Followers',
    iconName: 'account',
    iconType: 'material-community',
    showRightIcon: false,
    showLeftIcon: false,
  },
];

export const settingsItemArray = [
  {
    title: 'Account',
    navigateTo: 'Account',
    iconName: 'account',
    iconType: 'material-community',
    showRightIcon: true,
    showLeftIcon: true,
  },
  {
    title: 'Notifications',
    navigateTo: 'Notifications',
    iconName: 'notifications',
    iconType: 'ionicon',
    showRightIcon: true,
    showLeftIcon: true,
  },
  {
    title: 'Privacy and Security',
    navigateTo: 'PrivacyAndSecurity',
    iconName: 'lock',
    iconType: 'entypo',
    showRightIcon: true,
    showLeftIcon: true,
  },
  {
    title: 'Manage Payments',
    navigateTo: 'ManagePayments',
    iconName: 'payment',
    iconType: 'material',
    showRightIcon: true,
    showLeftIcon: true,
  },
  {
    title: 'Connect to Socials',
    navigateTo: 'ConnectToSocials',
    iconName: 'share-google',
    iconType: 'evilicon',
    showRightIcon: true,
    showLeftIcon: true,
  },
  {
    title: 'Help and Support',
    navigateTo: 'HelpAndSupport',
    iconName: 'headset-mic',
    iconType: 'material',
    showRightIcon: true,
    showLeftIcon: true,
  },
  {
    title: 'About',
    navigateTo: 'About',
    iconName: 'question',
    iconType: 'antdesign',
    showRightIcon: true,
    showLeftIcon: true,
  },
];

export default projectSingle;
